# 1. Introducción


* Breve descripción general de Pandas y su importancia.
* Discusión sobre SQL y su relación con las operaciones de Pandas DataFrame.

# 2. Setup

In [ ]:
import sqlite3 # a module in Python's standard library that provides an interface to the SQLite database.
import pandas as pd

In [ ]:
url = "https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv"
titanic_data = pd.read_csv(url)

In [ ]:
conn = sqlite3.connect(':memory:')
titanic_data.to_sql('titanic', conn, index=False)

887

**sqlite3.connect()** es una función que establece una conexión a una base de datos SQLite. Cuando se proporciona el argumento ':memory:', se le indica a SQLite que cree una nueva base de datos en la RAM. La principal ventaja de utilizar una base de datos en memoria es la velocidad.

**.to_sql()** es un método proporcionado por Pandas DataFrames que le permite escribir el contenido del DataFrame en una base de datos SQL.

El primer argumento 'titanic' es el nombre de la tabla que se creará en la base de datos SQLite.

El segundo argumento conn es el objeto de conexión que creamos anteriormente. Le indica al método .to_sql() dónde crear la tabla.

El argumento index=False le indica a Pandas que no escriba el índice del DataFrame como una columna separada en la base de datos. Si omitiera este argumento, obtendría una columna adicional llamada 'index' en su tabla SQL.

Función para ejecutar las queries (solamente ejecutarlo, no dará resultado)

In [ ]:
# Function to run querys
def run_query(query, connection=conn):
    return pd.read_sql_query(query, connection)

# 3. SQL vs. Pandas

Para **SQL** nuestra tabla se llama *titanic*

Para **pandas** nuestro df se llama *titanic_data*

In [ ]:
#Veo mis datos
titanic_data

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500



*   **Ver los nombres de 10 pasajeros**

In [ ]:
# Usando SQL

run_query(
"""
SELECT name
FROM titanic
LIMIT 10

"""

 )

                                                Name
0                             Mr. Owen Harris Braund
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                              Miss. Laina Heikkinen
3        Mrs. Jacques Heath (Lily May Peel) Futrelle
4                            Mr. William Henry Allen
5                                    Mr. James Moran
6                             Mr. Timothy J McCarthy
7                      Master. Gosta Leonard Palsson
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9                 Mrs. Nicholas (Adele Achem) Nasser

In [ ]:
# Usando Pandas
titanic_data.head(10)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708

**¿Cuántas clases diferentes hay?**

In [ ]:
# Usando SQL

run_query(
"""
SELECT DISTINCT pclass
FROM titanic

"""
    )

   Pclass
0       3
1       1
2       2

In [ ]:
# Usando Pandas
titanic_data["Pclass"].unique()

array([3, 1, 2])

**Mostrar los pasajeros ordenados por edad**

In [ ]:
# Usando SQL

run_query(
"""
SELECT name, age
FROM titanic
ORDER BY age


"""
    )

                                    Name    Age
0         Master. Assad Alexander Thomas   0.42
1               Master. Viljo Hamalainen   0.67
2           Miss. Helene Barbara Baclini   0.75
3                  Miss. Eugenie Baclini   0.75
4           Master. Alden Gates Caldwell   0.83
..                                   ...    ...
882                  Mr. Patrick Connors  70.50
883             Mr. George B Goldschmidt  71.00
884               Mr. Ramon Artagaveytia  71.00
885                   Mr. Johan Svensson  74.00
886  Mr. Algernon Henry Wilson Barkworth  80.00

[887 rows x 2 columns]

In [ ]:
# Usando Pandas
titanic_data.sort_values(by="Age")

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
799,1,3,Master. Assad Alexander Thomas,male,0.42,0,1,8.5167
751,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000
641,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583
466,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583
77,1,2,Master. Alden Gates Caldwell,male,0.83,0,2,29.0000
...,...,...,...,...,...,...,...,...
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500
490,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0,49.5042
95,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542
847,0,3,Mr. Johan Svensson,male,74.00,0,0,7.7750
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.00,0,0,30.0000

**Mostrar los pasajeros que sobrevivieron**

In [ ]:
# Usando SQL

run_query(
"""
SELECT COUNT(name)
FROM titanic
WHERE survived = 1

"""
    )

   COUNT(name)
0          342

In [ ]:
# Usando Pandas

titanic_data[titanic_data["Survived"]==1]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
...,...,...,...,...,...,...,...,...
871,1,3,Miss. Adele Kiamie Najib,female,15.0,0,0,7.2250
875,1,1,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,female,56.0,0,1,83.1583
876,1,2,Mrs. William (Imanita Parrish Hall) Shelley,female,25.0,0,1,26.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000

**Mostrar los pasajeros que no sobrevivieron y tenían menos de 30 años**

In [ ]:
# Usando SQL

run_query(
"""
SELECT name
FROM titanic
WHERE survived = 0 AND age < 30

"""
    )

                                    Name
0                 Mr. Owen Harris Braund
1                        Mr. James Moran
2          Master. Gosta Leonard Palsson
3          Mr. William Henry Saundercock
4    Miss. Hulda Amanda Adolfina Vestrom
..                                   ...
300          Miss. Gerda Ulrika Dahlberg
301         Mr. Frederick James Banfield
302                Mr. Henry Jr Sutehall
303                 Rev. Juozas Montvila
304       Miss. Catherine Helen Johnston

[305 rows x 1 columns]

In [ ]:
# Usando Pandas

titanic_data.loc[(titanic_data["Survived"]==0) & (titanic_data["Age"]<30)]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
...,...,...,...,...,...,...,...,...
878,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
879,0,2,Mr. Frederick James Banfield,male,28.0,0,0,10.5000
880,0,3,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500

Mostrar pasajeron que tienen entre 30 y 50 años

In [ ]:
# Usando SQL

run_query(
"""
SELECT COUNT(*)
FROM titanic
WHERE age BETWEEN 30 AND 50
"""
    )

   COUNT(*)
0       323

In [ ]:
# Usando Pandas

titanic_data.loc[(titanic_data["Age"] > 30) & (titanic_data["Age"] < 50)]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
...,...,...,...,...,...,...,...,...
868,0,1,Mr. Frans Olof Carlsson,male,33.0,0,0,5.0000
869,0,3,Mr. Victor Vander Cruyssen,male,47.0,0,0,9.0000
877,0,3,Mr. Johann Markun,male,33.0,0,0,7.8958
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

**¿Cuántos pasajeros se llaman 'John'?**

In [ ]:
# Usando SQL


run_query(
"""
select count (name)
from titanic
where name like '%John%'


"""
    )

   count (name)
0            52

In [ ]:
# Usando Pandas

titanic_data.loc[titanic_data["Name"].str.contains("John")].shape[0]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
41,0,2,Mrs. William John Robert (Dorothy Ann Wonnacot...,female,27.0,1,0,21.0000
44,0,3,Mr. William John Rogers,male,30.0,0,0,8.0500
97,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34.0,0,1,23.0000
111,0,3,Mr. David John Barton,male,22.0,0,0,8.0500
116,0,2,Mr. William John Robert Turpin,male,29.0,1,0,21.0000
159,0,3,Mr. John Hatfield Cribb,male,44.0,0,1,16.1000
161,0,3,Mr. John Viktor Bengtsson,male,26.0,0,0,7.7750
164,1,3,Master. Frank John William Goldsmith,male,9.0,0,2,20.5250
167,0,1,Mr. John D Baumann,male,60.0,0,0,25.9250
171,1,3,Miss. Eleanor Ileen Johnson,female,1.0,1,1,11.1333
187,0,3,Mr. John Bourke,male,40.0,1,1,15.5000
211,0,3,Mr. John Henry Perkin,male,22.0,0,0,7.2500
225,1,2,Mr. William John Mellors,male,19.0,0,0,10.5000
226,0,3,Mr. John Hall Lovell,male,20.5,0,0,7.2500
300,0,3,Mr. William Cahoone Jr Johnson,male,19.0,0,0,0.0000
322,0,3,Mr. George John Jr Sage,male,20.0,8,2,69.5500
326,1,3,Mrs. Frank John (Emily Alice Brown) Goldsmith,female,31.0,1,1,20.5250
399,0,3,Mr. John Adams,male,26.0,0,0,8.0500
416,0,2,Mr. William John Matthews,male,30.0,0,0,13.0000
464,0,1,Mr. John Montgomery Smart,male,56.0,0,0,26.5500
524,0,1,Mr. John Farthing,male,49.0,0,0,221.7792
545,0,3,Mr. Frank John Goldsmith,male,33.0,1,1,20.5250
546,1,2,Master. John Morgan Jr Davies,male,8.0,1,1,36.7500
547,1,1,Mr. John Borland Jr Thayer,male,17.0,0,2,110.8833
560,0,3,Mr. John Simmons,male,40.0,0,0,8.0500
569,1,1,Mr. John Irwin Flynn,male,36.0,0,0,26.3875
571,0,3,Mr. Alfred George John Rush,male,16.0,0,0,8.0500
578,1,1,Mrs. John Borland (Marian Longstreth Morris) T...,female,39.0,1,1,110.8833
580,0,1,Mr. John Hugo Ross,male,36.0,0,0,40.1250
583,0,2,Mr. John Denzil Jarvis,male,47.0,0,0,15.0000
591,0,2,Mr. John Henry Chapman,male,37.0,1,0,26.0000
594,0,3,Mr. Alfred Johnson,male,49.0,0,0,0.0000
610,0,3,Mr. John Horgan,male,22.0,0,0,7.7500
621,0,3,Mr. David John Bowen,male,21.0,0,0,16.1000
654,0,3,Mrs. John (Catherine) Bourke,female,32.0,1,1,15.5000
691,0,1,Col. John Weir,male,60.0,0,0,26.5500
695,0,1,Mr. John Borland Thayer,male,49.0,1,1,110.8833
697,1,1,Mrs. John Jacob (Madeleine Talmadge Force) Astor,female,18.0,1,0,227.5250
715,0,3,Mr. Malkolm Joackim Johnson,male,33.0,0,0,7.7750
729,0,2,Mr. William John Berriman,male,23.0,0,0,13.0000
756,0,3,Mr. John Garfirth,male,23.0,0,0,14.5000
761,1,1,Mrs. John C (Anna Andrews) Hogeboom,female,51.0,1,0,77.9583
779,0,3,Mr. Andrew G Johnston,male,35.0,1,2,23.4500
814,0,3,Mr. John Fredrik Alexander Holm,male,43.0,0,0,6.4500
818,0,1,Jonkheer. John George Reuchlin,male,38.0,0,0,0.0000
821,0,3,Mr. John Flynn,male,36.0,0,0,6.9500
844,0,2,Rev. John Harper,male,28.0,0,1,33.0000
860,0,2,Mr. John William Gill,male,24.0,0,0,13.0000
865,1,3,Master. Harold Theodor Johnson,male,4.0,1,1,11.1333
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500